### ISSUE TITLE
Deploy Jupyter to our stack

### ISSUE THREAD

**Issue by karfai** [Xalgorithms/interlibr#9]

**Comment by jpotvin** [comment]
Or, Jupyter Lab with Binder
https://readthedocs.org/projects/jupyterlab-tutorial/downloads/pdf/latest/
https://jupyterlab-tutorial.readthedocs.io/en/latest/
https://mybinder.org/

**Comment by karfai** [comment]
The work in https://github.com/Xalgorithms/xalgo-author is moving along nicely. Jupyter can be considered *back-burner* now.
